### ISSUE TITLE
Create clang-tidy config file

### ISSUE THREAD

**Issue by Elluran** [Mstrutov/Desbordante#142]
To make clang-tidy's checks results more accurate and useful we need to add .clang-tidy config, which specifies what checks clang-tidy should perform.

Don't forget to update corresponding workflow file, so it uses this config file. 
PR: https://github.com/Mstrutov/Desbordante/pull/132 can be helpful to understand how to do that.

**Comment by polyntsov** [comment]
Fixed in #139
