### ISSUE TITLE
Fix ValueFromStr for DoubleType

### ISSUE THREAD

**Issue by Sched71** [Mstrutov/Desbordante#150]
`expected_ranges` contains string representations of double values. `num_type` has `std::unique_ptr<model::INumericType>` type. `byte_ranges.ranges` has `std::vector<const std::byte *>` type.
For `"7.4"` string in `expected_ranges`, when compairing `expected` to the value from `byte_ranges.ranges`, which string representation returned by `byte_ranges.num_type->ValueToString` equals `"7.4"`, the `EXPECT_EQ` fails:
``` 
    auto expected = std::unique_ptr<std::byte[]>(byte_ranges.num_type->Allocate());
    for (size_t i = 0; i < expected_ranges.size(); ++i) {
        byte_ranges.num_type->ValueFromStr(expected.get(), expected_ranges[i]);
        EXPECT_EQ(byte_ranges.num_type->Compare(expected.get(), byte_ranges.ranges[i]),
                  model::CompareResult::kEqual);
    }
```
But string representation of `expected` is `"7.4"`, so the `EXPECT_EQ` in the code below succeeds:
``` 
    auto expected = std::unique_ptr<std::byte[]>(byte_ranges.num_type->Allocate());
    for (size_t i = 0; i < expected_ranges.size(); ++i) {
        byte_ranges.num_type->ValueFromStr(expected.get(), expected_ranges[i]);
        EXPECT_EQ(byte_ranges.num_type->ValueToString(expected.get()),
                  byte_ranges.num_type->ValueToString(byte_ranges.ranges[i])); 
    }
```
Also I want to note, that values in `byte_ranges.ranges` were obtained by `NumericType::Add`

Also see https://github.com/Mstrutov/Desbordante/pull/124#discussion_r1026187015

**Comment by polyntsov** [comment]
https://github.com/Mstrutov/Desbordante/pull/124#discussion_r1026187015
